export const projectsEn = {
  pageTitle: 'Projects',
  pageSubtitle: 'Substantial projects I led or contributed to — with context, approach, and outcomes.',
  tabs: {
    internship: 'Internship Projects',
    academic: 'Academic Projects',
    personal: 'Personal Projects',
  },
  panelDescriptions: {
    internship: 'One focused project per engagement: what it was, how I approached it, and what we delivered.',
    academic: 'Research and coursework projects: problem, methodology, and results.',
    personal: 'Side projects and self-directed work outside work and coursework.',
  },
  sectionTitles: {
    approach: 'How I approached it',
    outcomes: 'Key outcomes',
    viewProject: 'View project →',
  },
  internship: [
    {
      title: 'Multilingual Scraping & Price Benchmarking',
      company: 'OC&C',
      role: 'Data Analysis Consulting Project Intern',
      period: 'Oct 2025 – Jan 2026',
      cover: 'image/multilingual-scraping.png',
      teaser: 'One end-to-end project: pipelines and dashboards for cross-market price benchmarking.',
      description: 'I owned one major project: designing and building the data pipelines and dashboards that enabled cross-market price benchmarking for a global retail client. The project covered multilingual product scraping and matching, Power BI dashboards for localised pricing and sales actions, and competitor assortment, pricing architecture, and channel strategy benchmarks across retail, e‑commerce, and delivery. The goal was to turn scattered local data into a single, comparable view so the client could make pricing and range decisions across markets.',
      approach: 'I treated it as one project with a clear pipeline: ingest (scraping and cleaning), match (cross-market product alignment), and present (dashboards and recommendations). I started with a small pilot in two languages to validate matching logic and data quality before scaling. For scraping I used Python with explicit handling of encodings, local site structures, and rate limits. For matching I defined a product key (brand, category, attributes) and built rules and fuzzy matching so we could compare like-for-like across countries. I documented the pipeline and handover so the team could run and extend it after my internship.',
      points: [
        'Python pipelines for multilingual product scraping and matching — ~70% improvement in cross-market price-comparison accuracy',
        'Power BI dashboards and client-ready recommendations for localised pricing and sales actions',
        'Competitor assortment, pricing architecture, and channel strategy benchmarks (retail, e‑commerce, delivery)',
      ],
    },
    {
      title: 'E‑commerce Analytics',
      company: 'IPSOS (Strategy3)',
      role: 'Consulting Intern',
      period: 'Aug 2025 – Oct 2025',
      cover: 'image/ipsos-ecommerce.png',
      teaser: 'Product and pricing data integration, brand performance, and cross-country analytics for e‑commerce.',
      description: 'I contributed to an e‑commerce analytics and strategy engagement: integrating product and pricing data across markets, defining metrics for brand and price position, and building cross-country comparisons. The work supported client decisions on assortment, pricing architecture, and channel strategy. I also supported global expert interviews on international manufacturers’ localisation strategies for China, with themes fed into the analytics narrative.',
      approach: 'I framed the work around clear questions (e.g. how do we compare like-for-like across countries?) and defined data sources and a single deliverable structure. I integrated product and pricing data, built metrics for brand performance and price position, and compared across countries with consistent definitions. For the China localisation piece I helped design the interview guide and synthesised expert views into themes. I kept a simple project log so we could track assumptions and sources.',
      points: [
        'E‑commerce product and pricing data integration; brand performance and cross-country pricing structures',
        'Competitor and channel analytics to support assortment and pricing decisions',
        'Global expert interviews on international manufacturers’ localisation strategies for China',
      ],
    },
    {
      title: 'Raman Analytics',
      company: 'Merck',
      role: 'Clinical Data Analysis Intern',
      period: 'Jun 2025 – Sep 2025',
      cover: 'image/IMG_1795.png',
      teaser: 'Analytical models for Raman-based experiments; component prediction accuracy to ~90%.',
      description: 'I worked on a Raman analytics project: building and validating analytical models for Raman-based experiments to predict component composition, with accuracy taken to around 90%. I started by understanding the existing Raman pipeline and data structure, then built and validated the component prediction models with a train/validate split and clear accuracy metrics. I documented the methodology and assumptions so the team could replicate and extend the work.',
      approach: 'I treated it as one analytics project with a clear flow: raw Raman data → validated models → prediction outputs. I reviewed the existing pipeline and data specs, then built the component prediction models with proper train/validate splits and reported accuracy metrics. I documented the methodology and assumptions so the team could replicate and extend the work.',
      points: [
        'Analytical models for Raman-based experiments — component prediction accuracy to ~90%',
      ],
    },
    {
      title: 'Credit Risk Model Optimization',
      company: 'Oliver Wyman',
      role: 'Data Analysis Consulting Project Intern',
      period: 'Sep 2024 – Apr 2025',
      cover: 'image/credit-risk-model.png',
      teaser: 'One engagement: credit risk model optimisation and Basel III–aligned reporting.',
      description: 'I was staffed on one client engagement focused on credit risk model optimisation and Basel III–aligned reporting. The project involved optimising PD and LGD models, improving predictive accuracy by about 18%, and building Python and SQL automation for model updates and reporting so that cycles were roughly 30% faster. I also helped diagnose model weaknesses and identify a small set of main drivers of default risk from a long list of candidate factors. The deliverable was a single, coherent “model and process” upgrade that the client could use for both compliance and decision-making.',
      approach: 'I approached it as one project with a clear sequence: understand current models and process, identify improvement levers, implement and validate, then automate and document. I started by reviewing the existing PD/LGD models and the regulatory requirements so we had a shared baseline. I then ran variable importance and stability analysis to find the main drivers of default and proposed a simplified factor set that kept performance but improved interpretability. I built the automation so that data ingestion, model run, and report generation were in one pipeline, with clear handover and runbooks for the client team.',
      points: [
        'Optimised credit risk models (PD, LGD); Basel III compliance; predictive accuracy improved by ~18%',
        'Python and SQL automation for model updates and reporting — ~30% faster cycles',
        'Diagnosis of model weaknesses; identification of main drivers of default risk from 30+ candidate factors',
      ],
    },
    {
      title: 'Hospital Partnership Launch & Evaluation',
      company: 'AstraZeneca',
      role: 'Business Operations Intern',
      period: 'Jul 2024 – Sep 2024',
      cover: 'image/IMG_6007.JPG',
      teaser: 'One initiative: launch and evaluation of a major AstraZeneca–hospital partnership.',
      description: 'I supported one initiative: the launch and evaluation of a major AstraZeneca–hospital partnership. My role was to help coordinate across functions, track progress, and support stakeholder communication so that the partnership could be launched and evaluated in a structured way. The project aimed for high partner satisfaction (e.g. 95% satisfaction from key hospital partners) and tailored solutions for business expansion. I did not run the partnership itself but ensured that the “launch and evaluation” work was one clearly scoped project with defined milestones and feedback loops.',
      approach: 'I treated the launch and evaluation as one project with a simple plan: define success criteria and milestones, set up cross-functional coordination (meetings, ownership, escalation), and design a light-touch feedback mechanism from hospital partners. I helped draft communication and materials so that internal and external stakeholders had a consistent view of scope and timeline. I also supported the team in capturing lessons and refining the evaluation framework so that the same approach could be reused for future partnerships.',
      points: [
        'Support for launch and evaluation of major AstraZeneca–hospital partnership projects',
        'Cross-functional coordination; high satisfaction rate from key hospital partners',
        'Streamlined stakeholder communication and tailored solutions for business expansion',
      ],
    },
  ],
  academic: [
    // Liver Cancer Immune — commented out for now
    // {
    //   title: 'Liver Cancer Immune Microenvironment & Therapeutic Modeling',
    //   period: 'May 2024 – Nov 2024',
    //   context: 'Bioinformatics / Computational Biology',
    //   teaser: 'One research project: immune microenvironment and treatment-response modeling in liver cancer.',
    //   description: 'I led one research project on the pro-tumorigenic role of immune cells in the liver cancer microenvironment and built computational models to predict treatment response when targeting stromal cells. The work combined analysis of public and in-house data with mechanistic-style models implemented in Python so we could explore how different cell types and interventions might affect outcomes. The project was scoped as a single thesis-style piece with a clear question, methodology, and set of results.',
    //   approach: 'I framed the project around one main question: how do specific immune and stromal populations in the liver cancer microenvironment influence tumor progression and response to stromal-targeted therapy? I started with a literature and data review to define the cell types and pathways of interest, then built a pipeline for processing and integrating the data. I implemented the computational models in Python with explicit assumptions and parameters, validated on held-out or external data where possible, and ran sensitivity analyses to see which factors drove the predictions. I wrote the work up as one coherent narrative: motivation, methods, results, and implications.',
    //   points: [
    //     'Analysis of pro-tumorigenic immune cell mechanisms in the liver cancer microenvironment',
    //     'Computational models predicting treatment response when targeting stromal cells (Python)',
    //   ],
    // },
    {
      title: 'Predicting Protein Subcellular Localization',
      period: 'Mar 2025 – May 2025',
      context: 'Computational Biology',
      cover: 'image/protein-subcellular.png',
      teaser: 'Five-class ensemble (RF, GBM, class specialists) with Biopython feature extraction, SMOTE, and a three-tier confidence system.',
      description: 'I built a machine learning pipeline to predict protein subcellular localization (cytosolic, extracellular/secreted, mitochondrial, nuclear, other) from amino acid sequences. Using Biopython I extracted 143 sequence-derived features per protein: global properties (length, molecular weight, isoelectric point, aromaticity, instability index, GRAVY), full amino acid composition, N-terminal (20) and C-terminal (50) residues, and motif/pattern matching for targeting signals. After feature selection I kept the 69 most informative features (e.g. n_hydrophobicity, hydrophobic_density, n_negative, molecular_weight_kDa, length, starts_with_M, mito_score). The dataset was class-imbalanced, so I applied SMOTE to balance all five classes to 2189 samples each before training. I designed a two-stage ensemble: general models (Random Forest and Gradient Boosting, tuned with GridSearchCV) plus class-specific specialist models (one per class, where applicable). Ensemble blending weights were tuned per class on a 15% stratified hold-out validation set (F1 as the main metric). The specialised ensemble reached 72.62% test accuracy (vs 69.19% baseline RF), with strong performance on Extr and Othr and remaining confusion between Cyto and Nucl. I added a three-tier confidence system (High, Medium, Low) using class-specific probability thresholds derived from validation-set distributions; high-confidence predictions reached ~90% accuracy. The same pipeline was applied to a blind test set (20 sequences), achieving 75% accuracy, with predictions and confidence levels reported.',
      approach: 'I structured the work as a single end-to-end pipeline. (1) Feature extraction: FASTA sequences loaded with Biopython; for each protein I computed global physicochemical descriptors, per-residue composition, terminal windows (N 20, C 50), and motif scores (e.g. positive charge, hydrophobicity, targeting signals). (2) Data processing: train/test split (stratified, 80/20), then on the training side I applied feature selection (keeping 69 features), scaling, and SMOTE to balance the five classes; the same selection and scaler were applied to test and blind data. (3) Model design: I trained a baseline Random Forest, then an ensemble that combines RF, Gradient Boosting, and per-class specialists (GBM or RF or SVC depending on class). For each class I tuned the blending weights (RF, GBM, specialist) on the hold-out validation set by grid-searching weight combinations and maximising F1. (4) Evaluation: I reported per-class and overall accuracy, precision, recall, F1, and confusion matrix; analysed Cyto–Nucl confusion; and defined class-specific confidence thresholds from the validation probability distributions so that High/Medium/Low tiers would reflect actual reliability (high-conf ~90% accurate). Blind predictions were produced with the same feature pipeline and confidence assignment.',
      points: [
        '143 Biopython features (global, composition, N/C-terminal, motifs) reduced to 69; SMOTE to balance five classes',
        'Two-stage ensemble: RF + GBM + class specialists; per-class weights tuned on 15% hold-out (F1); 72.62% test accuracy, 75% blind test',
        'Three-tier confidence (High/Medium/Low) with class-specific thresholds; high-confidence predictions ~90% accurate',
      ],
    },
    {
      title: 'Fat–Water Separation in MRI (Bioimaging)',
      period: 'Mar 2025 – May 2025',
      context: 'Biomedical Imaging',
      cover: 'image/fat-water-mri.png',
      teaser: 'Multi-peak Dixon signal model, R2* decay, and multi-start optimization for PDFF and R2* maps from multi-echo MRI.',
      description: 'I implemented a full pipeline for quantitative fat fraction (PDFF) and R2* mapping from multi-echo magnitude MRI. The signal model uses a six-peak fat spectrum (relative amplitudes and chemical-shift frequencies from the literature) plus water, with R2* decay; I also explored a dual-R2* variant (separate decay for water and fat) to study stability. Because we fit magnitude-only data, fat–water ambiguity is inherent—I visualised how different water/fat amplitude pairs produce similar magnitude curves and used multi-start constrained optimisation (fmincon with bounds on amplitudes and R2*) to reduce local-minimum failures. I compared a least-squares objective on magnitude with a Rician negative log-likelihood to better match the noise model. Validation was hierarchical: first on simulated signals with known parameters and additive complex Gaussian noise (then magnitude, so effective Rician), then on in vivo DICOM multi-echo data. The in vivo pipeline loads 4D DICOM (slices × echo times), runs voxel-wise fitting in parallel, and post-processes the PDFF and R2* maps with median filtering and light Gaussian smoothing for robustness.',
      approach: 'I structured the work in three layers. (1) Signal model and ambiguity: I coded three variants—single-peak fat with no decay, multi-peak fat with no decay, and multi-peak plus single R2* decay—and plotted magnitude vs echo time and trajectories in the complex plane to see how different (ρw, ρf) pairs can give similar |S(t)|, which motivates multi-start and bounds. (2) Parameter estimation: For each voxel (or simulated signal), I minimised sum of squared errors between observed and model magnitude, with bounds [0,1] on water and fat amplitudes and [50, 90] s⁻¹ on R2* to match physiologically plausible values. I used 20 multi-start initialisations (water-dominant, fat-dominant, and random perturbations) and kept the fit with lowest SSE; I also added a Rician-likelihood objective and compared convergence and robustness. I guarded against division-by-zero when assessing “success” (clustering of solutions). (3) Real data: I wrote a DICOM loader that parses EchoTime and SliceLocation, selects magnitude images, and builds a 4D array (row × col × slice × echo). For each voxel I fit the multi-peak + R2* model once and wrote out both PDFF = ρf/(ρw+ρf) and R2* when the fit was within bounds and local SNR was sufficient, using raw magnitude (no synthetic noise on real data) and safe denominators when assessing success and error metrics; then I applied 2D median and Gaussian smoothing to produce the final PDFF and R2* maps.',
      points: [
        'Six-peak fat spectrum + water + R2* decay; magnitude-only fitting and fat–water ambiguity analysis',
        'Multi-start constrained optimisation (fmincon); comparison of SSE vs Rician likelihood; dual-R2* stability study',
        '4D DICOM loading, parallel voxel-wise fitting, and median + Gaussian smoothing for PDFF and R2* maps',
      ],
    },
    // Decoding Brain Activity — commented out for now
    // {
    //   title: 'Decoding Brain Activity for Semantic Video Content Translation',
    //   period: 'Apr 2024 – Dec 2024',
    //   context: 'NLP / Neuroscience',
    //   teaser: 'One research project: decoding semantic video content from brain activity and mapping to LLM space.',
    //   description: 'I contributed to one research project that aimed to decode semantic video content from brain activity recorded while participants watched videos, and to map those brain signals to large language model (LLM) representations. The project was scoped as a single research initiative with a clear question (can we decode “what” is being watched from brain activity?) and a methodology that linked neuroscience and NLP.',
    //   approach: 'I approached it as one project with two main steps: (1) decode relevant features from brain activity (e.g. via encoding models or dimensionality reduction), and (2) align those features to an LLM or semantic space so that the decoded content could be interpreted or translated. I helped design the experimental and analysis pipeline, made sure that train/test splits respected time or subject so we did not leak information, and documented the choices so the work could be replicated and extended.',
    //   points: [
    //     'Methods to decode semantic video content from brain activity during video viewing',
    //     'Mapping brain signals to large language model representations',
    //   ],
    // },
    {
      title: 'League of Legends Match Outcome Prediction',
      period: 'Feb 2024 – Mar 2024',
      context: 'Data Science / ML',
      cover: 'image/league-of-legends.png',
      link: 'https://ailinnastar.github.io/LeagueOfLegends/',
      teaser: 'One data science project: full pipeline from raw match data to outcome prediction and fairness analysis.',
      description: 'I completed one data science project that took raw League of Legends match data through cleaning, imputation, hypothesis testing, feature engineering, and model training to predict match outcome (reaching about 88% accuracy), with a fairness analysis across player segments. The project was run as a single end-to-end pipeline so that every step—from data quality to model choice to evaluation—was documented and reproducible.',
      approach: 'I treated it as one project with a clear sequence: understand the data, define the prediction task, build features, train and tune models, then evaluate and check fairness. I started by cleaning the data and handling missing values in a way that was explicit and repeatable. I then defined a set of features (e.g. champion picks, roles, historical performance) and used hypothesis testing where it helped (e.g. which features differed across outcomes). I trained several model families, tuned hyperparameters with a proper validation set, and reported accuracy on a held-out test set. I also ran a fairness-style analysis across player segments so we could see if the model behaved differently for different groups.',
      points: [
        'Data cleaning, missing value imputation, hypothesis testing on large-scale match data',
        'Feature engineering and hyperparameter tuning — ~88% prediction accuracy; fairness analysis across player segments',
      ],
    },
  ],
  personal: [
    {
      title: 'Stablecoin-Based Cross-Border E-Commerce Payments',
      period: 'Ongoing',
      context: 'Web3 / Personal Research',
      points: [
        'Comparison of traditional vs stablecoin-based cross-border payment flows; fees, FX risk, and regulation',
        'Scenario-based models for settlement costs and capital lock-up; impact on cross-border seller unit economics',
      ],
    },
  ],
}
